import{a as B,S as M,G as O,i as p}from"./assets/vendor-tnS95ulj.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const q=B.create({baseURL:"https://pixabay.com/api/",params:{key:"53374429-639c77152d70b3fe75f006246",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0}});async function L(s,t){return(await q.get("",{params:{q:s,page:t,per_page:15}})).data}let P={galleryElem:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".js-btn-load")};const{galleryElem:h,loader:d,loadMoreBtn:m}=P;function v({webformatURL:s,largeImageURL:t,tags:a,likes:i,views:e,comments:o,downloads:n}){let S=a.split(",").slice(0,3);return`
  <li class="list-item">
        <div class="item-container">
        <a href="${t}" class="">
          <img src="${s}" alt="${S}" class="item-img">
          </a>
          <div class="desc-container">
            <p class="item-title">Likes <span class="item-number">${i}</span></p>
            <p class="item-title">Views <span class="item-number">${e}</span></p>
            <p class="item-title">Comments <span class="item-number">${o}</span></p>
            <p class="item-title">Downloads <span class="item-number">${n}</span></p>
          </div>
        </div>
      </li>`}const b=new M(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250,overlayOpacity:.85});function $(s){const t=s.map(v).join("");return h.innerHTML=t,b.refresh(),t}function A(s){const t=s.map(v).join("");return h.insertAdjacentHTML("beforeend",t),b.refresh(),t}function y(){h.innerHTML=""}function w(){d.classList.contains("isActive")||d.classList.add("isActive")}function f(){d.classList.contains("isActive")&&d.classList.remove("isActive")}function j(){m.classList.contains("hidden")?m.classList.remove("hidden"):console.log("⚠️ class hidden its alredy  REMOVED ")}function D(){m.classList.contains("hidden")?console.log("⚠️ class hidden its alredy  ADDED"):m.classList.add("hidden")}function G(){new O({element:"#granim-canvas",name:"granim",opacity:[1,1],states:{"default-state":{gradients:[["#834D9B","#D04ED6"],["#1CD8D2","#93EDC7"]]}}})}const T={form:document.querySelector(".form"),loadMoreBtn:document.querySelector(".js-btn-load")},{form:c,loadMoreBtn:x}=T;document.addEventListener("DOMContentLoaded",()=>{G()});const C=15;let r,l,g,u;c.addEventListener("submit",async s=>{if(s.preventDefault(),l=new FormData(c).get("search-text").trim(),r=1,l==="")return y(),c.reset(),p.show({messageSize:"20",message:"Будь ласка введіть назву фото!",position:"center",close:!0,closeOnEscape:!0,theme:"light",color:"yellow"});w(),y(),c.reset();try{const a=await L(l,r);if(a.hits.length===0)return f(),Promise.reject(reject);$(a.hits),g=Math.ceil(a.total/C),console.log("Total Pages",g),f(),E()}catch{p.show({messageSize:"20",message:"На жаль, немає зображень, що відповідають вашому пошуковому запиту. Спробуйте ще раз!",position:"center",close:!0,closeOnEscape:!0,theme:"light",color:"orange"})}});x.addEventListener("click",async()=>{r+=1;const s=document.querySelector(".list-item");u=s.getBoundingClientRect(),console.log(s),console.log(u),w(),D();const t=await L(l,r);A(t.hits),f(),E(),window.scrollBy({top:u.height*3,behavior:"smooth"})});function E(){r<g?j():(D(),p.show({messageSize:"20",message:"Вибачте, але ви досягли кінця результатів пошуку.",position:"bottomCenter",close:!0,closeOnEscape:!0,theme:"light",color:"white"}))}
//# sourceMappingURL=index.js.map
